---
linters:
  disable-all: true
  enable:
  - errcheck
  - gochecknoinits
  - goconst
  - gocritic
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - typecheck
  - unconvert
  - unused
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
