# Documentation at http://goreleaser.com
---
project_name: hammer
before:
  hooks:
  - go mod download
builds:
- main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
archives:
- id: archive
  format: "tar.gz"
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
brews:
- tap:
    owner: pivotal
    name: hammer
  ids:
  - archive
  test: |
    system "#{bin}/hammer version"
changelog:
