---
language: go

go:
- "1.13"

env:
- GO111MODULE=on

install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
- go get github.com/onsi/ginkgo/ginkgo@v1.10.1
- go mod download

script:
- golangci-lint run
- ginkgo -r .

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
