# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage ""
  version "0.13.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal/hammer/releases/download/v0.13.1/hammer_darwin_amd64.tar.gz"
      sha256 "1085cd901fb6791c37492776ebb05d26bb8f2956efc2080321ad8455fafdf2be"

      define_method(:install) do
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pivotal/hammer/releases/download/v0.13.1/hammer_darwin_arm64.tar.gz"
      sha256 "3fa03f3bc868b075afd188300eb297ddc0663d2af76a5b43f3853f6e900146fe"

      define_method(:install) do
        bin.install "hammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal/hammer/releases/download/v0.13.1/hammer_linux_amd64.tar.gz"
      sha256 "01b49f14af28372c335f47fcef35cd061739496ccdee7763d0d247cc25b315d4"
      define_method(:install) do
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal/hammer/releases/download/v0.13.1/hammer_linux_arm64.tar.gz"
      sha256 "de88fd241537e5d5776b71473dd3b9381379cc686b7f8a54acc706b370d2778b"
      define_method(:install) do
        bin.install "hammer"
      end
    end
  end

  test do
    system "#{bin}/hammer version"
  end
end
