---
name: Test
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: Check out code
      uses: actions/checkout@v6
    - name: Unit tests
      run: |
        make unit-test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
